import type {
  EnterpriseOrder,
  EnterpriseOrderValues,
} from './enterpriseOrders.types';

export const toOrderFormValues = (
  order: EnterpriseOrder,
): EnterpriseOrderValues => ({
  balance_due: Number(order.balance_due),
  billing_address_line1: order.billing_address_line1,
  billing_city: order.billing_city,
  billing_country: order.billing_country,
  billing_postal_code: order.billing_postal_code,
  billing_state: order.billing_state,
  carrier: order.carrier,
  created_at: order.created_at,
  customer_email: order.customer_email,
  customer_id: order.customer_id,
  customer_name: order.customer_name,
  customer_phone: order.customer_phone,
  customer_rating: order.customer_rating,
  customer_since: order.customer_since,
  customer_type: order.customer_type,
  delivery_date: order.delivery_date ?? '',
  discount_amount: Number(order.discount_amount),
  discount_percentage: Number(order.discount_percentage),
  estimated_delivery_days: order.estimated_delivery_days,
  internal_notes: order.internal_notes ?? '',
  is_fragile: order.is_fragile,
  is_gift: order.is_gift,
  is_rush_order: order.is_rush_order,
  is_vip_customer: order.is_vip_customer,
  last_modified_by: order.last_modified_by,
  loyalty_points: order.loyalty_points,
  order_date: order.order_date,
  order_id: order.order_id,
  order_notes: order.order_notes ?? '',
  order_number: order.order_number,
  order_status: order.order_status,
  order_timestamp: order.order_timestamp,
  paid_amount: Number(order.paid_amount),
  payment_date: order.payment_date ?? '',
  payment_method: order.payment_method,
  payment_reference: order.payment_reference ?? '',
  payment_status: order.payment_status,
  priority: order.priority,
  product_category: order.product_category,
  product_subcategory: order.product_subcategory,
  quantity: order.quantity,
  requires_signature: order.requires_signature,
  shipped_date: order.shipped_date ?? '',
  shipping_address_line1: order.shipping_address_line1,
  shipping_address_line2: order.shipping_address_line2 ?? '',
  shipping_city: order.shipping_city,
  shipping_cost: Number(order.shipping_cost),
  shipping_country: order.shipping_country,
  shipping_postal_code: order.shipping_postal_code,
  shipping_state: order.shipping_state,
  subtotal: Number(order.subtotal),
  tax_amount: Number(order.tax_amount),
  total_amount: Number(order.total_amount),
  tracking_number: order.tracking_number ?? '',
  unit_price: Number(order.unit_price),
  updated_at: order.updated_at,
  volume_m3: Number(order.volume_m3),
  warehouse_location: order.warehouse_location,
  weight_kg: Number(order.weight_kg),
});
