import { defineConfig } from 'vite-plus';

import { createFmtConfig } from '@repo/vite-configs/fmt';
import { lintSharedConfig } from '@repo/vite-configs/lint';

const fmtConfig = createFmtConfig({
  // `reports/sonar/` is machine-generated by `scripts/sonar-report.mjs` with
  // `JSON.stringify(…, null, 2)` — the same stable convention the other report
  // generators use. Sonar findings carry populated short arrays (e.g. issue
  // `tags`) that Oxfmt collapses onto one line, so the generator and formatter
  // would fight and churn the file on every run. Keep Oxfmt out of it; the
  // generator's output is the canonical, deterministic format.
  // `reports/pr-queue/` is the same case: `scripts/pr-queue-operator.mjs` writes
  // each pass's decision log with the same stable `JSON.stringify(…, null, 2)`
  // convention, and the markdown alongside it is generated too.
  ignorePatterns: [
    '.react-router/',
    'build/',
    'reports/pr-queue/',
    'reports/sonar/',
  ],
});

export default defineConfig({
  fmt: fmtConfig,
  // Vite+ reads `lint` from this file only; a workspace's own `lint` block is
  // never loaded. Per-workspace differences are `overrides` inside this config.
  lint: lintSharedConfig,
  run: {
    tasks: {
      build: {
        // Orchestrator — individual package tasks handle their own caching
        cache: false,
        command: 'vp run -r build',
      },
    },
  },
  staged: {
    '*': 'vp check --fix',
    // `vp check` is fmt + Oxlint + tsgolint and knows nothing about Biome, so
    // without this entry the Biome gate would only ever fail in CI — after the
    // commit it was supposed to block. Check-only on purpose: unlike the
    // `--fix` above, a Biome autofix here could rewrite a staged file after it
    // was reviewed, so a violation fails the commit and `vp run lint:biome`
    // applies the fix deliberately.
    '*.{ts,tsx,mjs,cjs}': 'biome lint --no-errors-on-unmatched',
  },
});
