/**
 * Every workspace in this repo, classified by runtime.
 *
 * It lives here, not in `@lcabrera/vite-config`, because it is this repo's own
 * directory roster and no consumer's (ADR-069) — and here specifically because
 * the root config is already this repo's one lint-config home (ADR-042).
 * `vp run lint:plugins:verify` fails if a workspace is missing from all three
 * lists, or if a glob here names a workspace that no longer exists, and reads
 * this export to do it.
 *
 * `env` only supplies globals to the `no-undef` family, which is not enabled
 * today, so these are inert as rules and exact as documentation. They become
 * load-bearing the moment a category containing `no-undef` is turned on, which
 * is why they are kept correct rather than deleted.
 *
 * `lintConfig` is exported for the same reason: `packages/repo-standards/scripts/verify-lint-plugins.mjs`
 * reads the live plugin list off it.
 */

import { defineConfig } from 'vite-plus';

import { createFmtConfig } from '@lcabrera/vite-config/fmt';
import { createLintConfig } from '@lcabrera/vite-config/lint';

export const WORKSPACE_RUNTIMES = {
  /**
   * Neither runtime, and so neither set of globals. `@lcabrera/utils` guarantees
   * pure, side-effect-free helpers: its tsconfig gives it no DOM lib and no node
   * types, and anything that must touch the process belongs in `@lcabrera/node`
   * instead. Handing it `process` here would contradict the boundary the
   * tsconfig exists to enforce.
   */
  agnostic: ['packages/utils/**'],
  /** Workspaces whose code runs in a browser. */
  browser: [
    'apps/showcase/**',
    'packages/ui/**',
    // Browser-safe by construction — its tsconfig omits node types (ADR-038).
    'packages/api/**',
  ],
  /** Workspaces whose code runs in Node — services and build tooling alike. */
  node: [
    'packages/create-lcabrera-stack/**',
    'packages/devkit/**',
    'packages/node-runtime/**',
    'packages/repo-standards/**',
    'packages/server/**',
    'packages/eslint-local-rules/**',
    'packages/ts-configs/**',
    'packages/tsconfig/**',
    'packages/vite-configs/**',
  ],
};

const fmtConfig = createFmtConfig({
  // `reports/sonar/` is machine-generated by `scripts/sonar-report.mjs` with
  // `JSON.stringify(…, null, 2)` — the same stable convention the other report
  // generators use. Sonar findings carry populated short arrays (e.g. issue
  // `tags`) that Oxfmt collapses onto one line, so the generator and formatter
  // would fight and churn the file on every run. Keep Oxfmt out of it; the
  // generator's output is the canonical, deterministic format.
  // `reports/pr-queue/` is the same case: `scripts/pr-queue-operator.mjs` writes
  // each pass's decision log with the same stable `JSON.stringify(…, null, 2)`
  // convention, and the markdown alongside it is generated too.
  ignorePatterns: [
    '.react-router/',
    'build/',
    'reports/pr-queue/',
    'reports/sonar/',
  ],
});

const sharedLintConfig = createLintConfig({
  workspaceRuntimes: WORKSPACE_RUNTIMES,
});

export const lintConfig = {
  ...sharedLintConfig,
  // The application `@lcabrera/devkit` ships is a tree for a repository that
  // does not exist yet, and the type-aware pass can only read it as one of
  // ours: its imports resolve against the packages that repository installs
  // from the registry and against the tsconfig its own generator writes, and
  // neither is here, so every one of them reports unresolvable.
  //
  // This entry takes the WHOLE Oxlint pass off that subtree, not only the type
  // half, and nothing narrower is expressible: `typeAware`/`typeCheck` are
  // root-level `options`, and an override carries only `env`, `excludeFiles`,
  // `files`, `globals`, `jsPlugins`, `plugins` and `rules` — an override with
  // `plugins: []` was tried and leaves the type diagnostics running. Excluding
  // the directory from the root tsconfig does not stop them either.
  //
  // So `no-debugger` and the rest of the `correctness` category go unchecked
  // here by Oxlint. What still reads these files is Oxfmt, and the eslint pass
  // `packages/devkit` runs over its own directory — which carries `eslint`,
  // `unicorn`, `perfectionist`, `security`, `typescript-eslint` and the local
  // rules, and reports a planted `debugger` and an unused binding. That pass is
  // itself proven live by `vp run lint:eslint:verify`, whose probe roster names
  // this package for that reason. The rest runs where the tree lands: the
  // created repository's own `lint:check`.
  ignorePatterns: [
    ...(sharedLintConfig.ignorePatterns ?? []),
    'packages/devkit/assets/workspace/apps/',
  ],
};

export default defineConfig({
  fmt: fmtConfig,
  // Vite+ reads `lint` from this file only; a workspace's own `lint` block is
  // never loaded. Per-workspace differences are `overrides` inside this config.
  lint: lintConfig,
  run: {
    tasks: {
      build: {
        // Orchestrator — individual package tasks handle their own caching
        cache: false,
        command: 'vp run -r build',
      },
    },
  },
  staged: {
    // Every autofixer the repo has, ordered, under ONE glob.
    //
    // One glob because lint-staged runs separate entries concurrently: a second
    // entry that also writes would race the first over the same file, while
    // commands inside one entry run in sequence. Biome sat here check-only for
    // exactly that reason, which left its gate first failing in CI — after the
    // commit it was meant to block.
    //
    // Writing is safe in this hook and nowhere else in the flow: lint-staged
    // re-stages what a task changes, so a fix lands in the commit being made
    // rather than in the working tree behind it.
    //
    // `vp check --fix` is Oxfmt + Oxlint + the tsgolint type pass. Biome writes
    // its safe fixes only. `repo-eslint-staged` takes a trailing `--` because
    // lint-staged appends the filenames, and a leading `-` is legal in one.
    // It resolves each path to the
    // workspace whose `eslint.config.mjs` governs it and fixes there — there is
    // no root ESLint config to point a single invocation at. They all ignore
    // what they cannot lint, so one glob can carry files of any type.
    //
    // `vp fmt` closes the chain because a lint fixer only edits its own range:
    // deleting a `undefined,` argument can leave a call broken across lines that
    // now fits on one, which the formatter — the first stage, already past —
    // would print differently, so the commit succeeds and the push then fails on
    // formatting. Nothing may write after the formatter.
    '*': [
      'vp check --fix',
      'biome lint --write --no-errors-on-unmatched',
      'repo-eslint-staged --',
      'vp fmt',
    ],
  },
});
