import * as stylex from '@stylexjs/stylex';

import {
  borderRadius,
  shadows,
  spacing,
  typography,
} from '@/design-system/tokens/base.stylex';
import { colors } from '@/design-system/tokens/colors.stylex';

/* eslint-disable @stylexjs/sort-keys */

export const styles = stylex.create({
  bodyCell: {
    alignItems: 'center',
    color: colors.textPrimary,
    display: 'flex',
    borderRightColor: colors.borderSecondary,
    borderRightStyle: 'solid',
    fontFamily: typography.fontFamilyMono,
    borderRightWidth: '1px',
    fontSize: typography.fontSizeXs,
    lineHeight: typography.lineHeightNormal,
    padding: `${spacing.sm} ${spacing.md}`,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  bodyCellLast: {
    borderRightWidth: 0,
  },
  bodyRow: {
    backgroundColor: colors.backgroundPrimary,
    display: 'flex',
    position: 'absolute',
    borderBottomColor: colors.borderSecondary,
    borderBottomStyle: 'solid',
    borderBottomWidth: '1px',
    left: 0,
    right: 0,
    width: '100%',
  },
  container: {
    gap: spacing.lg,
    marginInline: 'auto',
    padding: spacing.xl,
    display: 'flex',
    flexDirection: 'column',
    maxWidth: '100%',
  },
  description: {
    margin: 0,
    color: colors.textSecondary,
    fontSize: typography.fontSizeMd,
    lineHeight: typography.lineHeightRelaxed,
  },
  devNotice: {
    borderColor: colors.warning,
    borderRadius: borderRadius.lg,
    borderStyle: 'solid',
    borderWidth: '1px',
    backgroundColor: colors.warningBackground,
    color: colors.warningText,
    fontSize: typography.fontSizeSm,
    margin: 0,
    lineHeight: typography.lineHeightRelaxed,
    padding: spacing.md,
  },
  errorState: {
    borderColor: colors.error,
    borderRadius: borderRadius.lg,
    borderStyle: 'solid',
    borderWidth: '1px',
    backgroundColor: colors.errorBackground,
    color: colors.error,
    fontSize: typography.fontSizeSm,
    margin: 0,
    lineHeight: typography.lineHeightRelaxed,
    padding: spacing.md,
  },
  footer: {
    alignItems: 'center',
    backgroundColor: colors.backgroundSecondary,
    color: colors.textSecondary,
    display: 'flex',
    padding: spacing.md,
    borderTopColor: colors.borderPrimary,
    fontSize: typography.fontSizeSm,
    borderTopStyle: 'solid',
    justifyContent: 'space-between',
    borderTopWidth: '1px',
  },
  footerError: {
    color: colors.error,
    fontWeight: typography.fontWeightSemibold,
  },
  footerFetching: {
    color: colors.brandPrimary,
    fontWeight: typography.fontWeightSemibold,
  },
  header: {
    gap: spacing.md,
    alignItems: 'end',
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  headerButton: {
    borderColor: 'transparent',
    borderStyle: 'none',
    borderWidth: 0,
    alignItems: 'center',
    backgroundColor: 'transparent',
    color: colors.textPrimary,
    gap: spacing.xs,
    cursor: 'default',
    padding: spacing.md,
    display: 'flex',
    fontFamily: 'inherit',
    fontSize: typography.fontSizeSm,
    fontWeight: typography.fontWeightSemibold,
    justifyContent: 'space-between',
    textAlign: 'left',
    width: '100%',
  },
  headerButtonSortable: {
    cursor: 'pointer',
  },
  headerButtonSorted: {
    color: colors.brandPrimary,
  },
  headerCell: {
    alignItems: 'stretch',
    display: 'flex',
    borderBottomColor: colors.borderPrimary,
    borderBottomStyle: 'solid',
    borderBottomWidth: '1px',
  },
  headerCopy: {
    gap: spacing.xs,
    display: 'flex',
    flexDirection: 'column',
    maxWidth: '72ch',
  },
  headerLabel: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  headerRow: {
    display: 'flex',
    width: '100%',
  },
  loadingState: {
    padding: spacing.xl,
    color: colors.textSecondary,
    fontSize: typography.fontSizeMd,
  },
  sortIndicator: {
    color: colors.textTertiary,
    fontSize: typography.fontSizeXs,
    textAlign: 'right',
    minWidth: '1.5rem',
  },
  statusPill: {
    borderColor: colors.borderPrimary,
    borderRadius: borderRadius.full,
    borderStyle: 'solid',
    borderWidth: '1px',
    alignItems: 'center',
    backgroundColor: colors.backgroundSecondary,
    padding: `${spacing.xs} ${spacing.md}`,
    color: colors.textSecondary,
    gap: spacing.xs,
    display: 'inline-flex',
    fontSize: typography.fontSizeSm,
    fontWeight: typography.fontWeightMedium,
  },
  table: {
    borderCollapse: 'separate',
    borderSpacing: 0,
    display: 'grid',
    minWidth: '100%',
  },
  tableBody: {
    display: 'grid',
    position: 'relative',
  },
  tableHead: {
    backgroundColor: colors.backgroundSecondary,
    display: 'grid',
    position: 'sticky',
    zIndex: 1,
    top: 0,
  },
  tableScroller: {
    overflow: 'auto',
    position: 'relative',
    height: '72vh',
    maxHeight: '860px',
    minHeight: '520px',
  },
  tableSurface: {
    borderColor: colors.borderPrimary,
    borderRadius: borderRadius.xl,
    borderStyle: 'solid',
    borderWidth: '1px',
    overflow: 'hidden',
    backgroundColor: colors.backgroundPrimary,
    boxShadow: shadows.md,
  },
  title: {
    margin: 0,
    color: colors.textPrimary,
    fontSize: typography.fontSize2xl,
    fontWeight: typography.fontWeightBold,
  },
});
