import type { EnterpriseOrderInput } from './enterpriseOrders.schema';

export const buildValidOrderFormFields = (): Record<string, string> => ({
  billing_address_line1: '221B Baker Street',
  billing_city: 'London',
  billing_country: 'UK',
  billing_postal_code: 'NW1 6XE',
  billing_state: 'Greater London',
  carrier: 'FedEx',
  customer_email: 'ada@example.com',
  customer_id: '42',
  customer_name: 'Ada Lovelace',
  customer_phone: '+1 (555) 123-4567',
  customer_since: '2020-01-01',
  customer_type: 'Individual',
  discount_percentage: '10',
  estimated_delivery_days: '3',
  loyalty_points: '120',
  order_date: '2024-02-01',
  order_status: 'Pending',
  paid_amount: '50',
  payment_method: 'Credit Card',
  payment_status: 'Partially Paid',
  priority: 'High',
  product_category: 'Electronics',
  product_subcategory: 'Laptops',
  quantity: '2',
  shipping_address_line1: '1 Infinite Loop',
  shipping_city: 'Cupertino',
  shipping_cost: '5',
  shipping_country: 'USA',
  shipping_postal_code: '95014',
  shipping_state: 'CA',
  unit_price: '100',
  volume_m3: '0.5',
  warehouse_location: 'Warehouse A',
  weight_kg: '1.2',
});

export const buildValidOrderInput = (): EnterpriseOrderInput => ({
  billing_address_line1: '221B Baker Street',
  billing_city: 'London',
  billing_country: 'UK',
  billing_postal_code: 'NW1 6XE',
  billing_state: 'Greater London',
  carrier: 'FedEx',
  customer_email: 'ada@example.com',
  customer_id: 42,
  customer_name: 'Ada Lovelace',
  customer_phone: '+1 (555) 123-4567',
  customer_rating: 5,
  customer_since: '2020-01-01',
  customer_type: 'Individual',
  delivery_date: '',
  discount_percentage: 10,
  estimated_delivery_days: 3,
  internal_notes: '',
  is_fragile: false,
  is_gift: false,
  is_rush_order: true,
  is_vip_customer: true,
  loyalty_points: 120,
  order_date: '2024-02-01',
  order_notes: 'Leave at the door.',
  order_status: 'Pending',
  paid_amount: 50,
  payment_date: '',
  payment_method: 'Credit Card',
  payment_reference: '',
  payment_status: 'Partially Paid',
  priority: 'High',
  product_category: 'Electronics',
  product_subcategory: 'Laptops',
  quantity: 2,
  requires_signature: false,
  shipped_date: '',
  shipping_address_line1: '1 Infinite Loop',
  shipping_address_line2: '',
  shipping_city: 'Cupertino',
  shipping_cost: 5,
  shipping_country: 'USA',
  shipping_postal_code: '95014',
  shipping_state: 'CA',
  tracking_number: '',
  unit_price: 100,
  volume_m3: 0.5,
  warehouse_location: 'Warehouse A',
  weight_kg: 1.2,
});
