import type {
  ColumnPinningState,
  TableCrudConfig,
  TableColumn,
} from '@repo/ui/components/Table/Table.types';

import {
  createBasicColumn,
  createDistinctStringColumn,
} from '@repo/ui/components/Table/utils';
import { createStaticFilterOptions } from '@repo/ui/utils/filters';

import { type EnterpriseOrder, enterpriseOrdersApi } from '@/services';

export const TITLE = {
  plural: 'Enterprise Orders',
  singular: 'Order',
};
export const TABLE_NAME = 'enterprise_orders';
export const SCHEMA_NAME = 'public';

export const PERSISTENCE_KEY = 'enterprise-orders-table';

export const CRUD: TableCrudConfig<EnterpriseOrder> = {
  create: true,
  delete: true,
  deleteActionPath: '/_action/enterprise-orders/delete',
  idAccessor: 'order_id',
  read: true,
  update: true,
};

export const DEFAULT_COLUMN_PINNING: ColumnPinningState<EnterpriseOrder> = {
  left: [],
  right: ['actions'],
};

export const COLUMNS: TableColumn<EnterpriseOrder>[] = [
  createBasicColumn({
    dataType: 'number',
    key: 'order_id',
    label: 'Order ID',
    maxWidth: 120,
    minWidth: 90,
  }),
  createDistinctStringColumn({
    columnName: 'order_number',
    fetchDistinctValues: enterpriseOrdersApi.fetchDistinctValues,
    key: 'order_number',
    label: 'Order #',
    maxWidth: 180,
    minWidth: 130,
  }),
  createBasicColumn({
    dataType: 'date',
    key: 'order_date',
    label: 'Order Date',
    maxWidth: 150,
    minWidth: 120,
  }),
  {
    dataType: 'string',
    ...createStaticFilterOptions<EnterpriseOrder>([
      'Cancelled',
      'Delivered',
      'On Hold',
      'Pending',
      'Processing',
      'Refunded',
      'Returned',
      'Shipped',
    ]),
    key: 'order_status',
    label: 'Status',
    maxWidth: 150,
    minWidth: 110,
  },
  {
    dataType: 'string',
    ...createStaticFilterOptions<EnterpriseOrder>([
      'Critical',
      'High',
      'Low',
      'Normal',
      'Urgent',
    ]),
    key: 'priority',
    label: 'Priority',
    maxWidth: 130,
    minWidth: 100,
  },
  createBasicColumn({
    dataType: 'string',
    key: 'customer_name',
    label: 'Customer',
    maxWidth: 250,
    minWidth: 150,
  }),
  createDistinctStringColumn({
    columnName: 'customer_email',
    fetchDistinctValues: enterpriseOrdersApi.fetchDistinctValues,
    key: 'customer_email',
    label: 'Email',
    maxWidth: 280,
    minWidth: 180,
  }),
  createDistinctStringColumn({
    columnName: 'customer_type',
    fetchDistinctValues: enterpriseOrdersApi.fetchDistinctValues,
    key: 'customer_type',
    label: 'Customer Type',
    maxWidth: 180,
    minWidth: 130,
  }),
  createBasicColumn({
    dataType: 'boolean',
    key: 'is_vip_customer',
    label: 'VIP',
    maxWidth: 100,
    minWidth: 70,
  }),
  createBasicColumn({
    dataType: 'number',
    key: 'loyalty_points',
    label: 'Loyalty Points',
    maxWidth: 150,
    minWidth: 120,
  }),
  createBasicColumn({
    dataType: 'currency',
    key: 'total_amount',
    label: 'Total Amount',
    maxWidth: 180,
    minWidth: 130,
  }),
  createBasicColumn({
    dataType: 'currency',
    key: 'subtotal',
    label: 'Subtotal',
    maxWidth: 150,
    minWidth: 110,
  }),
  createBasicColumn({
    dataType: 'currency',
    key: 'tax_amount',
    label: 'Tax',
    maxWidth: 130,
    minWidth: 100,
  }),
  createBasicColumn({
    dataType: 'currency',
    key: 'shipping_cost',
    label: 'Shipping',
    maxWidth: 130,
    minWidth: 100,
  }),
  createBasicColumn({
    dataType: 'currency',
    key: 'discount_amount',
    label: 'Discount',
    maxWidth: 130,
    minWidth: 100,
  }),
  {
    dataType: 'string',
    ...createStaticFilterOptions<EnterpriseOrder>([
      'Cancelled',
      'Failed',
      'Paid',
      'Partially Paid',
      'Pending',
      'Refunded',
    ]),
    key: 'payment_status',
    label: 'Payment Status',
    maxWidth: 160,
    minWidth: 130,
  },
  {
    dataType: 'string',
    ...createStaticFilterOptions<EnterpriseOrder>([
      'Bank Transfer',
      'Cash',
      'Check',
      'Credit Card',
      'Cryptocurrency',
      'Debit Card',
      'PayPal',
    ]),
    key: 'payment_method',
    label: 'Payment Method',
    maxWidth: 180,
    minWidth: 140,
  },
  createBasicColumn({
    dataType: 'string',
    key: 'product_category',
    label: 'Category',
    maxWidth: 220,
    minWidth: 140,
  }),
  createBasicColumn({
    dataType: 'string',
    key: 'product_subcategory',
    label: 'Subcategory',
    maxWidth: 180,
    minWidth: 130,
  }),
  createBasicColumn({
    dataType: 'number',
    key: 'quantity',
    label: 'Quantity',
    maxWidth: 120,
    minWidth: 90,
  }),
  createBasicColumn({
    dataType: 'currency',
    key: 'unit_price',
    label: 'Unit Price',
    maxWidth: 150,
    minWidth: 110,
  }),
  createDistinctStringColumn({
    columnName: 'shipping_city',
    fetchDistinctValues: enterpriseOrdersApi.fetchDistinctValues,
    key: 'shipping_city',
    label: 'Ship City',
    maxWidth: 180,
    minWidth: 120,
  }),
  createDistinctStringColumn({
    columnName: 'shipping_state',
    fetchDistinctValues: enterpriseOrdersApi.fetchDistinctValues,
    key: 'shipping_state',
    label: 'Ship State',
    maxWidth: 150,
    minWidth: 110,
  }),
  createDistinctStringColumn({
    columnName: 'shipping_country',
    fetchDistinctValues: enterpriseOrdersApi.fetchDistinctValues,
    key: 'shipping_country',
    label: 'Ship Country',
    maxWidth: 180,
    minWidth: 130,
  }),
  createDistinctStringColumn({
    columnName: 'carrier',
    fetchDistinctValues: enterpriseOrdersApi.fetchDistinctValues,
    key: 'carrier',
    label: 'Carrier',
    maxWidth: 150,
    minWidth: 100,
  }),
  createDistinctStringColumn({
    columnName: 'warehouse_location',
    fetchDistinctValues: enterpriseOrdersApi.fetchDistinctValues,
    key: 'warehouse_location',
    label: 'Warehouse',
    maxWidth: 180,
    minWidth: 130,
  }),
  createBasicColumn({
    dataType: 'boolean',
    key: 'is_rush_order',
    label: 'Rush',
    maxWidth: 90,
    minWidth: 70,
  }),
  createBasicColumn({
    dataType: 'boolean',
    key: 'is_gift',
    label: 'Gift',
    maxWidth: 90,
    minWidth: 70,
  }),
  createBasicColumn({
    dataType: 'number',
    key: 'customer_rating',
    label: 'Rating',
    maxWidth: 110,
    minWidth: 80,
  }),
  createBasicColumn({
    dataType: 'date',
    key: 'delivery_date',
    label: 'Delivery Date',
    maxWidth: 150,
    minWidth: 130,
  }),
  createBasicColumn({
    dataType: 'date',
    key: 'shipped_date',
    label: 'Shipped Date',
    maxWidth: 150,
    minWidth: 130,
  }),
  {
    isFilterable: false,
    isHeaderHidden: true,
    isResizable: false,
    isSortable: false,
    isStatic: true,
    key: 'actions',
    label: 'Actions',
    maxWidth: 32,
    minWidth: 32,
  },
];
