export const fmtConfig = {
  arrowParens: 'always',
  bracketSpacing: true,
  endOfLine: 'lf',
  ignorePatterns: [
    '.react-router/',
    'build/',
    'dist/',
    'miscelanious/',
    'node_modules/',
    'eslint-local-rules/',
  ],
  jsxSingleQuote: true,
  printWidth: 80,
  semi: true,
  singleQuote: true,
  sortPackageJson: false,
  tabWidth: 2,
  trailingComma: 'all',
} as const;
