type BuildRunnerScriptScaffoldArgs = {
  readonly displayName: string;
  readonly rawArtifactFileName?: string;
  readonly scannerId: string;
};

/**
 * Deterministic runner-script scaffold for a registry-added scanner
 * (ADR-023) — wired to the shared deterministic-scan machinery with a
 * marked, unimplemented parser block. (The *emitted* script carries a
 * literal task marker, which is the point of the scaffold; this description
 * spells it out rather than repeating the token, so the sentence is not read
 * as an open task in this file.) Deliberately emits a valid 0-findings report
 * so a half-registered scanner degrades gracefully instead of crashing
 * the queue. The registry never overwrites an existing script: the code
 * on disk stays authoritative, and the orchestrator only executes paths
 * registered in DETERMINISTIC_SCANNER_CONFIGS (a code change).
 */
export const buildRunnerScriptScaffold = ({
  displayName,
  rawArtifactFileName,
  scannerId,
}: BuildRunnerScriptScaffoldArgs): string => {
  const rawFileName = rawArtifactFileName ?? `${scannerId}.raw.json`;

  return String.raw`#!/usr/bin/env node
// ${displayName} — deterministic runner scaffold generated by the CQMS
// scanner registry (ADR-023). Honors the shared deterministic-runner flag
// contract (--target/--scope/--output-dir/--skip-ingest). Replace the TODO
// parser block below; everything else is already wired. To let the
// orchestrator execute this scanner, also register it in
// apps/scan-orchestrator/src/queue/queue.constants.ts
// (a deliberate code change — DB rows never name executables).

import {
  ingestScanArtifacts,
  makeFindingId,
  makeTimestamp,
  parseRunContext,
  resolveOutputDirectory,
  writeArtifacts,
} from '@repo/scan-report/deterministic-scan';

const context = parseRunContext();

const main = () => {
  const timestamp = makeTimestamp();
  const outputDirectory = resolveOutputDirectory(
    context,
    '${scannerId}',
    timestamp,
  );

  // TODO(parser): run the underlying tool against context.scopeDirectory,
  // keep its verbatim output as the raw artifact, and map each result to a
  // canonical finding via makeFindingId (see generate-eslint-report.mjs and
  // generate-fallow-report.mjs for reference implementations). Per-row
  // detail data goes under rawArtifact.rows — sp_ingest_generic_detail
  // ingests each element into this scanner's cqms.scanner_detail_* table.
  const findings = [];
  const rawArtifact = { kind: '${scannerId}', rows: [] };
  void makeFindingId;

  const report = {
    blocker_count: 0,
    files_analyzed: 0,
    findings,
    generated_at: new Date().toISOString(),
    high_count: 0,
    low_count: 0,
    medium_count: 0,
    nit_count: 0,
    report_id: '${scannerId}-' + timestamp,
    top_risk: 'TODO parser block not implemented yet — 0 findings emitted.',
  };

  const markdown = [
    '# ${scannerId} Report',
    '',
    '## Metadata',
    '',
    '- schema_version: 1.0',
    '- report_id: ' + report.report_id,
    '- generated_at: ' + report.generated_at,
    '- skill_name: ${scannerId}',
    '- scope_type: folder',
    '- scope_value: ' + context.scopeArgument,
    '- severity_scale: BLOCKER, HIGH, MEDIUM, LOW, NIT',
    '- raw_artifact: ${rawFileName}',
    '',
    '## Summary',
    '',
    '- files_analyzed: 0',
    '- top_risk: ' + report.top_risk,
    '',
    '## Findings',
    '',
    'No findings — TODO parser block not implemented yet.',
    '',
    '## Prioritized Execution Queue',
    '',
    'None — no findings.',
    '',
    '## Deferred Items',
    '',
    'None.',
  ].join('\n');

  writeArtifacts({
    markdown,
    outputDirectory,
    rawArtifact,
    rawFileName: '${rawFileName}',
    report,
  });

  console.log('Run directory: ' + outputDirectory + '/');

  ingestScanArtifacts({
    context,
    outputDirectory,
    rawFileName: '${rawFileName}',
    scannerId: '${scannerId}',
  });
};

main();
`;
};
