/**
 * Pure board rendering + parsing for the coordination register. `renderBoard`
 * builds BOARD.md from the task and branch data; `parseBoard` reads a committed
 * board back into comparable data so the verify step can diff DATA, not text
 * (Oxfmt reflowing the table is then invisible). No I/O here — the caller in
 * `verify-coordination.mjs` owns the file reads/writes. See `.claude/rules/scripts.md`.
 */

/** One row of task board data — the fields that define "who is working on what". */
export const boardTuple = (data) =>
  [data.id, data.status, data.owner, data.branch].join(' | ');

/** Wrap a value in backticks (own function so the template literal isn't nested). */
const code = (value) => `\`${value}\``;
const renderArea = (area) => area.map(code).join('<br>');

const HEADER =
  '# Coordination board\n\n' +
  '> Generated by `vp run coordination:board` from `tasks/*.md` + `branches/*.md`.\n' +
  '> Do not hand-edit — edit the source file, then regenerate. `vp run\n' +
  '> coordination:verify` fails if this drifts. See [README.md](./README.md).\n\n';

const renderTasks = (tasks) =>
  tasks
    .filter(({ data }) => data !== undefined)
    .map(({ data }) => data)
    .sort(
      (a, b) => a.status.localeCompare(b.status) || a.id.localeCompare(b.id),
    )
    .map(
      (d) =>
        `| [${d.title}](tasks/${d.id}.md) | ${d.owner} | ${d.status} | ` +
        `${code(d.branch)} | ${renderArea(d.area)} | ${d.updated} |`,
    )
    .join('\n');

const renderBranches = (branches, tasks) =>
  branches
    .filter(({ data }) => data !== undefined)
    .map(({ slug, data }) => {
      const participants = tasks
        .filter((t) => t.data?.branch === data.branch)
        .map((t) => t.data.id);
      return (
        `| [${code(data.branch)}](branches/${slug}.md) | ${data.base} → ${data.target} | ` +
        `${data.integrator} | ${data.status} | ${participants.join(', ') || '—'} | ${data.updated} |`
      );
    })
    .join('\n');

export const renderBoard = (tasks, branches) => {
  const hasTasks = tasks.some(({ data }) => data !== undefined);
  const hasBranches = branches.some(({ data }) => data !== undefined);
  if (!hasTasks && !hasBranches) {
    return `${HEADER}_No active tasks. Claim one by copying \`tasks/_TEMPLATE.md\`._\n`;
  }

  const tasksSection = hasTasks
    ? '## Tasks\n\n| Task | Owner | Status | Branch | Area | Updated |\n' +
      `| ---- | ----- | ------ | ------ | ---- | ------- |\n${renderTasks(tasks)}\n`
    : '';

  const branchesSection = hasBranches
    ? '\n## Shared branches\n\n| Branch | Base → Target | Integrator | Status | Participants | Updated |\n' +
      `| ------ | ------------- | ---------- | ------ | ------------ | ------- |\n${renderBranches(branches, tasks)}\n`
    : '';

  return `${HEADER}${tasksSection}${branchesSection}`;
};

/** Committed board → comparable data: task tuples + shared-branch slugs. */
export const parseBoard = (text) => {
  const tasks = new Set();
  const branches = new Set();
  for (const line of text.split('\n')) {
    const branchSlugMatch = /\]\(branches\/([\w-]+)\.md\)/.exec(line);
    if (branchSlugMatch !== null) {
      branches.add(branchSlugMatch[1]);
      continue;
    }
    const id = /\]\(tasks\/([\w-]+)\.md\)/.exec(line)?.[1];
    if (id === undefined) {
      continue;
    }
    const cells = line.split('|').map((c) => c.trim());
    // cells: ['', task, owner, status, branch, area, updated, '']
    tasks.add(
      [id, cells[3], cells[2], cells[4]?.replaceAll('`', '')].join(' | '),
    );
  }
  return { branches, tasks };
};
