/**
 * Two things the seeds have to keep, asserted against this repository rather
 * than against the packages that encode them.
 *
 * The first is the rule `verify-devkit-seeds.mjs` enforces, unit-tested on
 * literal content so a change to what counts as a finding is visible here rather
 * than only in a gate's exit code.
 *
 * The second is a drift check with no other home: the decision-home index is
 * SEEDED by `@repo/devkit` and GENERATED by `@repo/repo-standards`, and neither
 * package may depend on the other. If the generator's wording moves and the seed
 * does not, every consumer's first index reads as out of date the moment they
 * materialise it — and nothing in either package would say so.
 */

import { readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vite-plus/test';

import { renderIndex } from '../../packages/repo-standards/scripts/adr-registry.mjs';
import { DEFAULT_REGISTERS } from '../../packages/repo-standards/scripts/config.mjs';
import {
  brokenPlaceholdersIn,
  EXEMPTIONS,
  findingsIn,
  forbiddenWords,
  reportFor,
} from './devkit-seeds.mjs';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');

const words = forbiddenWords({
  repositoryName: 'vite-monorepo',
  secretNames: ['GITHUB_TOKEN', 'SONAR_TOKEN'],
  workspaceNames: ['@lcabrera/ui', '@repo/devkit'],
});

describe('forbiddenWords', () => {
  it('carries the repository, its workspaces, its secrets and its runner', () => {
    expect(words).toContain('vite-monorepo');
    expect(words).toContain('@lcabrera/ui');
    expect(words).toContain('secrets.SONAR_TOKEN');
    expect(words).toContain('vp ');
  });

  it('leaves the token every repository has', () => {
    // A seed legitimately reads `secrets.GITHUB_TOKEN`; forbidding it would make
    // the only portable way to authenticate a workflow a finding.
    expect(words).not.toContain('secrets.GITHUB_TOKEN');
  });
});

describe('findingsIn', () => {
  it('reports every occurrence with the line it sits on', () => {
    const findings = findingsIn({
      content: ['name: Check', '', '        run: vp run test:all'].join('\n'),
      path: 'workflows/check.yml',
      words,
    });
    expect(findings).toEqual([
      { line: 3, path: 'workflows/check.yml', word: 'vp ' },
    ]);
  });

  it('does not read the runner out of an ordinary word', () => {
    // `vp` bounded by a trailing space, so prose about a `.vphrase` or a
    // `vpn` is not a finding. Without the boundary the gate would report
    // findings nobody can act on, and be ignored.
    expect(
      findingsIn({ content: 'a vpn and a vp.', path: 'a.md', words }),
    ).toEqual([]);
  });
});

describe('reportFor', () => {
  const exemptions = [{ path: 'rules/x.md', reason: 'tracked in #1' }];

  it('holds back a finding in an exempted file', () => {
    const { reported, unused } = reportFor({
      exemptions,
      findings: [{ line: 1, path: 'rules/x.md', word: 'vp ' }],
    });
    expect(reported).toEqual([]);
    expect(unused).toEqual([]);
  });

  it('fails an exemption that covers nothing', () => {
    // The failure this catches is silent: an exemption that outlived its reason
    // goes on exempting whatever that file becomes next.
    const { reported, unused } = reportFor({ exemptions, findings: [] });
    expect(reported).toEqual([]);
    expect(unused).toEqual(exemptions);
  });

  it('reports a finding outside every exempted file', () => {
    const findings = [{ line: 4, path: 'workflows/check.yml', word: 'vp ' }];
    expect(reportFor({ exemptions, findings }).reported).toEqual(findings);
  });
});

describe('brokenPlaceholdersIn', () => {
  const at = (line) => brokenPlaceholdersIn({ content: line, path: 'a.yml' });

  it('accepts an interpolated placeholder and a declared key', () => {
    expect(at("        run: '{{commands.install}}'")).toEqual([]);
    expect(at('requires: [config.commands.install]')).toEqual([]);
  });

  it('reports the shape the formatter leaves behind', () => {
    // The exact rewrite: the formatter reads an unquoted `{{…}}` in a workflow
    // as a nested YAML flow mapping. The substituter's pattern then misses it,
    // so the braces are written into the consumer's tree and `sync` calls the
    // file materialised.
    expect(at('        run: { { commands.install } }')).toEqual([
      { line: 1, path: 'a.yml' },
    ]);
  });

  it('reports a key named with no placeholder around it at all', () => {
    expect(at('run: commands.install')).toEqual([{ line: 1, path: 'a.yml' }]);
  });

  it('says nothing about a line that names no command key', () => {
    expect(at('run: npm ci')).toEqual([]);
  });
});

describe('every exemption names where it is tracked', () => {
  it('so a reader can find out whether it is still true', () => {
    for (const entry of EXEMPTIONS) {
      expect(entry.reason).toMatch(/#\d+/);
    }
  });
});

describe('the seeded decision index', () => {
  it('is byte-identical to what the gate generates for a default home', () => {
    const seeded = readFileSync(
      join(REPO_ROOT, 'packages/devkit/assets/decisions/README.md'),
      'utf8',
    );
    expect(seeded).toBe(renderIndex(DEFAULT_REGISTERS.adrHomes[0]));
  });
});
