import type { SortRule } from 'api-shared';

const ENTERPRISE_ORDER_COLUMNS = [
  'balance_due',
  'billing_address_line1',
  'billing_city',
  'billing_country',
  'billing_postal_code',
  'billing_state',
  'carrier',
  'created_at',
  'customer_email',
  'customer_id',
  'customer_name',
  'customer_phone',
  'customer_rating',
  'customer_since',
  'customer_type',
  'delivery_date',
  'discount_amount',
  'discount_percentage',
  'estimated_delivery_days',
  'internal_notes',
  'is_fragile',
  'is_gift',
  'is_rush_order',
  'is_vip_customer',
  'last_modified_by',
  'loyalty_points',
  'order_date',
  'order_id',
  'order_notes',
  'order_number',
  'order_status',
  'order_timestamp',
  'paid_amount',
  'payment_date',
  'payment_method',
  'payment_reference',
  'payment_status',
  'priority',
  'product_category',
  'product_subcategory',
  'quantity',
  'requires_signature',
  'shipped_date',
  'shipping_address_line1',
  'shipping_address_line2',
  'shipping_city',
  'shipping_cost',
  'shipping_country',
  'shipping_postal_code',
  'shipping_state',
  'subtotal',
  'tax_amount',
  'total_amount',
  'tracking_number',
  'unit_price',
  'updated_at',
  'volume_m3',
  'warehouse_location',
  'weight_kg',
] as const;

export const ENTERPRISE_ORDER_ALLOWED_COLUMNS = new Set(
  ENTERPRISE_ORDER_COLUMNS,
);

export const ENTERPRISE_ORDER_DISTINCT_COLUMNS = new Set([
  'carrier',
  'customer_email',
  'customer_type',
  'order_number',
  'order_status',
  'payment_method',
  'payment_status',
  'priority',
  'product_category',
  'product_subcategory',
  'shipping_city',
  'shipping_country',
  'shipping_state',
  'warehouse_location',
]);

export const DEFAULT_ENTERPRISE_ORDER_SORTING = [
  { columnKey: 'order_id', direction: 'desc' },
] as const satisfies readonly SortRule[];
